---
- name: "Loading vars for {{ ansible_os_family }}"
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: "Installing for {{ ansible_os_family }}"
  include: "install-{{ ansible_os_family | lower }}.yml"
